<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.6 Multiple Regression in R | HDFS 523: Strategies for Data Analysis in Developmental Research</title>
  <meta name="description" content="Course notes for HDFS 523" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="5.6 Multiple Regression in R | HDFS 523: Strategies for Data Analysis in Developmental Research" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/image1.png" />
  <meta property="og:description" content="Course notes for HDFS 523" />
  <meta name="github-repo" content="zackfisher/HDFS523" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.6 Multiple Regression in R | HDFS 523: Strategies for Data Analysis in Developmental Research" />
  
  <meta name="twitter:description" content="Course notes for HDFS 523" />
  <meta name="twitter:image" content="/images/image1.png" />

<meta name="author" content="Zachary F. Fisher" />


<meta name="date" content="2022-01-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="null" type="image/x-icon" />
<link rel="prev" href="5.5-example-data-2.html"/>

<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course notes for HDFS 523</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About This Book</a>
<ul>
<li class="chapter" data-level="1.1" data-path="1.1-why-this-book.html"><a href="1.1-why-this-book.html"><i class="fa fa-check"></i><b>1.1</b> Why this book?</a></li>
<li class="chapter" data-level="1.2" data-path="1.2-code-folding.html"><a href="1.2-code-folding.html"><i class="fa fa-check"></i><b>1.2</b> Code Folding</a></li>
<li class="chapter" data-level="1.3" data-path="1.3-acknowledgements.html"><a href="1.3-acknowledgements.html"><i class="fa fa-check"></i><b>1.3</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-chapter-2.html"><a href="2-chapter-2.html"><i class="fa fa-check"></i><b>2</b> Data Cleaning</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2.1-example-data.html"><a href="2.1-example-data.html"><i class="fa fa-check"></i><b>2.1</b> Example Data</a></li>
<li class="chapter" data-level="2.2" data-path="2.2-reading-in-repeated-measures-data.html"><a href="2.2-reading-in-repeated-measures-data.html"><i class="fa fa-check"></i><b>2.2</b> Reading in Repeated Measures Data</a></li>
<li class="chapter" data-level="2.3" data-path="2.3-familiarize-yourself-with-the-data.html"><a href="2.3-familiarize-yourself-with-the-data.html"><i class="fa fa-check"></i><b>2.3</b> Familiarize Yourself with the Data</a></li>
<li class="chapter" data-level="2.4" data-path="2.4-look-for-duplicated-ids.html"><a href="2.4-look-for-duplicated-ids.html"><i class="fa fa-check"></i><b>2.4</b> Look for Duplicated IDs</a></li>
<li class="chapter" data-level="2.5" data-path="2.5-using-table-to-spot-irregularities.html"><a href="2.5-using-table-to-spot-irregularities.html"><i class="fa fa-check"></i><b>2.5</b> Using <code>table()</code> to Spot Irregularities</a></li>
<li class="chapter" data-level="2.6" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html"><i class="fa fa-check"></i><b>2.6</b> Missing Data</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#generating-example-data"><i class="fa fa-check"></i><b>2.6.1</b> Generating Example Data</a></li>
<li class="chapter" data-level="2.6.2" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#recoding-values-with-na"><i class="fa fa-check"></i><b>2.6.2</b> Recoding Values with <code>NA</code></a></li>
<li class="chapter" data-level="2.6.3" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#missing-data-visualization"><i class="fa fa-check"></i><b>2.6.3</b> Missing Data Visualization</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="2.7-exporting-data.html"><a href="2.7-exporting-data.html"><i class="fa fa-check"></i><b>2.7</b> Exporting Data</a></li>
<li class="chapter" data-level="2.8" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html"><i class="fa fa-check"></i><b>2.8</b> Reshaping Repeated Measures Data</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html#reshape-wide-to-long"><i class="fa fa-check"></i><b>2.8.1</b> Reshape Wide to Long</a></li>
<li class="chapter" data-level="2.8.2" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html#reshape-long-to-wide"><i class="fa fa-check"></i><b>2.8.2</b> Reshape Long to Wide</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-chapter-3.html"><a href="3-chapter-3.html"><i class="fa fa-check"></i><b>3</b> Describing Longitudinal Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3.1-example-data-1.html"><a href="3.1-example-data-1.html"><i class="fa fa-check"></i><b>3.1</b> Example Data</a></li>
<li class="chapter" data-level="3.2" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html"><i class="fa fa-check"></i><b>3.2</b> Describing Means and Variances</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html#verbal-ability-all-persons-and-occasions"><i class="fa fa-check"></i><b>3.2.1</b> Verbal Ability (All Persons and Occasions)</a></li>
<li class="chapter" data-level="3.2.2" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html#verbal-ability-across-time"><i class="fa fa-check"></i><b>3.2.2</b> Verbal Ability (Across Time)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="3.3-describing-covariances.html"><a href="3.3-describing-covariances.html"><i class="fa fa-check"></i><b>3.3</b> Describing Covariances</a></li>
<li class="chapter" data-level="3.4" data-path="3.4-individual-level-descriptives.html"><a href="3.4-individual-level-descriptives.html"><i class="fa fa-check"></i><b>3.4</b> Individual-Level Descriptives</a></li>
<li class="chapter" data-level="3.5" data-path="3.5-references.html"><a href="3.5-references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-chapter-4.html"><a href="4-chapter-4.html"><i class="fa fa-check"></i><b>4</b> Matrix Algebra Review</a>
<ul>
<li class="chapter" data-level="4.1" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html"><i class="fa fa-check"></i><b>4.1</b> Types of matrices</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#square"><i class="fa fa-check"></i><b>4.1.1</b> Square</a></li>
<li class="chapter" data-level="4.1.2" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#symmetric"><i class="fa fa-check"></i><b>4.1.2</b> Symmetric</a></li>
<li class="chapter" data-level="4.1.3" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#diagonal"><i class="fa fa-check"></i><b>4.1.3</b> Diagonal</a></li>
<li class="chapter" data-level="4.1.4" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#identity"><i class="fa fa-check"></i><b>4.1.4</b> Identity</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html"><i class="fa fa-check"></i><b>4.2</b> Operations on Matrices</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-transpose"><i class="fa fa-check"></i><b>4.2.1</b> Matrix Transpose</a></li>
<li class="chapter" data-level="4.2.2" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-trace"><i class="fa fa-check"></i><b>4.2.2</b> Matrix Trace</a></li>
<li class="chapter" data-level="4.2.3" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#addition"><i class="fa fa-check"></i><b>4.2.3</b> Addition</a></li>
<li class="chapter" data-level="4.2.4" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#subtraction"><i class="fa fa-check"></i><b>4.2.4</b> Subtraction</a></li>
<li class="chapter" data-level="4.2.5" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-multiplication"><i class="fa fa-check"></i><b>4.2.5</b> Matrix Multiplication</a></li>
<li class="chapter" data-level="4.2.6" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-division"><i class="fa fa-check"></i><b>4.2.6</b> Matrix Division</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-chapter-5.html"><a href="5-chapter-5.html"><i class="fa fa-check"></i><b>5</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5.1-linear-regression-model.html"><a href="5.1-linear-regression-model.html"><i class="fa fa-check"></i><b>5.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="5.2" data-path="5.2-ordinary-least-squares.html"><a href="5.2-ordinary-least-squares.html"><i class="fa fa-check"></i><b>5.2</b> Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="5.2-ordinary-least-squares.html"><a href="5.2-ordinary-least-squares.html#assumptions-of-ols"><i class="fa fa-check"></i><b>5.2.1</b> Assumptions of OLS</a></li>
<li class="chapter" data-level="5.2.2" data-path="5.2-ordinary-least-squares.html"><a href="5.2-ordinary-least-squares.html#properties-of-boldsymbolhatbeta"><i class="fa fa-check"></i><b>5.2.2</b> Properties of <span class="math inline">\(\boldsymbol{\hat{\beta}}\)</span></a></li>
<li class="chapter" data-level="5.2.3" data-path="5.2-ordinary-least-squares.html"><a href="5.2-ordinary-least-squares.html#failure-of-assumptions"><i class="fa fa-check"></i><b>5.2.3</b> Failure of Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5.3-regression-and-matrix-notation.html"><a href="5.3-regression-and-matrix-notation.html"><i class="fa fa-check"></i><b>5.3</b> Regression and Matrix Notation</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="5.3-regression-and-matrix-notation.html"><a href="5.3-regression-and-matrix-notation.html#an-intercept-only-model"><i class="fa fa-check"></i><b>5.3.1</b> An Intercept-Only Model</a></li>
<li class="chapter" data-level="5.3.2" data-path="5.3-regression-and-matrix-notation.html"><a href="5.3-regression-and-matrix-notation.html#intercept-only-model-in-matrix-form"><i class="fa fa-check"></i><b>5.3.2</b> Intercept-Only Model in Matrix Form</a></li>
<li class="chapter" data-level="5.3.3" data-path="5.3-regression-and-matrix-notation.html"><a href="5.3-regression-and-matrix-notation.html#simple-regression-in-matrix-form"><i class="fa fa-check"></i><b>5.3.3</b> Simple Regression in Matrix Form</a></li>
<li class="chapter" data-level="5.3.4" data-path="5.3-regression-and-matrix-notation.html"><a href="5.3-regression-and-matrix-notation.html#multiple-regression-in-matrix-form"><i class="fa fa-check"></i><b>5.3.4</b> Multiple Regression in Matrix Form</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5.4-solving-the-regression-equation.html"><a href="5.4-solving-the-regression-equation.html"><i class="fa fa-check"></i><b>5.4</b> Solving the Regression Equation</a></li>
<li class="chapter" data-level="5.5" data-path="5.5-example-data-2.html"><a href="5.5-example-data-2.html"><i class="fa fa-check"></i><b>5.5</b> Example Data</a></li>
<li class="chapter" data-level="5.6" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html"><i class="fa fa-check"></i><b>5.6</b> Multiple Regression in R</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html#intercept-only-model"><i class="fa fa-check"></i><b>5.6.1</b> Intercept-Only Model</a></li>
<li class="chapter" data-level="5.6.2" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html#simple-linear-regression"><i class="fa fa-check"></i><b>5.6.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="5.6.3" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html#mean-centering-predictors"><i class="fa fa-check"></i><b>5.6.3</b> Mean Centering Predictors</a></li>
<li class="chapter" data-level="5.6.4" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html#multiple-linear-regression"><i class="fa fa-check"></i><b>5.6.4</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="5.6.5" data-path="5.6-multiple-regression-in-r.html"><a href="5.6-multiple-regression-in-r.html#interactions"><i class="fa fa-check"></i><b>5.6.5</b> Interactions</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/zackfisher/HDFS523" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">HDFS 523: Strategies for Data Analysis in Developmental Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-regression-in-r" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Multiple Regression in R</h2>
<p>For the first example, we focus on verbal ability at Grade 2 as an outcome (<code>verb2</code> in the data frame <code>wiscsub</code>). Examining the distribution for ‘verb2.’</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="5.6-multiple-regression-in-r.html#cb53-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(wiscsub<span class="sc">$</span>verb2)</span></code></pre></div>
<pre><code>##    vars   n  mean   sd median trimmed  mad  min   max range  skew kurtosis   se
## X1    1 204 25.42 6.11  25.98    25.4 6.57 5.95 39.85  33.9 -0.06    -0.34 0.43</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="5.6-multiple-regression-in-r.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>verb2)) <span class="sc">+</span> </span>
<span id="cb55-2"><a href="5.6-multiple-regression-in-r.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">2.5</span>, <span class="at">fill=</span><span class="st">&quot;white&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">boundary=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="5.6-multiple-regression-in-r.html#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Verbal Ability Grade 2&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb55-4"><a href="5.6-multiple-regression-in-r.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="5.6-multiple-regression-in-r.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<div id="intercept-only-model" class="section level3" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Intercept-Only Model</h3>
<p>The simplest model is an intercept only model. In this case, we would fit the model</p>
<p><span class="math display">\[ verb_{2i} = b_0 + \epsilon_{i}\]</span></p>
<p>Written out explicitly with the “silent” 1 in it, we get
<span class="math display">\[ verb_{2i} = b_01_i + \epsilon_{i}\]</span>
This is helpful for explicit translation into the R code, specifically the <code>formula</code> within the <code>lm()</code> function.</p>
<p>We fit the model using the following code. Note that the code has the ‘1’ predictor variable stated explicitly.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="5.6-multiple-regression-in-r.html#cb56-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> verb2 <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb56-2"><a href="5.6-multiple-regression-in-r.html#cb56-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> wiscsub,</span>
<span id="cb56-3"><a href="5.6-multiple-regression-in-r.html#cb56-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span>
<span id="cb56-4"><a href="5.6-multiple-regression-in-r.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = verb2 ~ 1, data = wiscsub, na.action = na.exclude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.4653  -4.6403   0.5647   4.2822  14.4347 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  25.4153     0.4275   59.45   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.106 on 203 degrees of freedom</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="5.6-multiple-regression-in-r.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Note that we used <code>na.exclude</code> instead of <code>na.omit</code> (default); practically speaking <code>na.omit</code> deletes missing data entries while <code>na.exclude</code> just excludes from the analysis.Therefore with <code>na.exclude</code>, in the residuals and fitted values, <code>NA</code> will show up where there were missing values.</p>
<p>The output indicates that <span class="math inline">\(b_0\)</span> = 25.4153, and its standard error = 0.4275.</p>
<p>The intercept reflects the expected value of the outcome variable when all of the predictor variables (i.e. <span class="math inline">\(\left\{ x_{1i}, ..., x_{qi}\right\}\)</span>) = 0. So, in the absence of any additional information other than the descriptive statistics of <span class="math inline">\(verb_{2i}\)</span>, what is our best guess for a person’s <span class="math inline">\(verb_{2i}\)</span> score? It is the mean of <span class="math inline">\(verb_{2i}\)</span>. The regression above confirms this notion; regressing the outcome on a vector of 1s allows us to ‘recover’ the mean.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="5.6-multiple-regression-in-r.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(wiscsub<span class="sc">$</span>verb2)</span></code></pre></div>
<pre><code>## [1] 25.41534</code></pre>
<p>Yes - we recovered the <em>mean</em>, but we did not attempt to explain any of the <em>variance</em>. It thus makes sense that we get 0 as the R-square. With an intercept only model there is only residual variability; there is no variability due to the regression model itself because there are no predictors.</p>
</div>
<div id="simple-linear-regression" class="section level3" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Simple Linear Regression</h3>
<p>Let’s build up the model further. For example, we could attempt to explain some of the <em>between-person variance</em> in the Grade 2 verbal score from the Grade 1 verbal scores. But, before we do, let’s examine the distribution of the <em>between-person differences</em> in the Grade 1 verbal scores.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="5.6-multiple-regression-in-r.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>verb1)) <span class="sc">+</span> </span>
<span id="cb62-2"><a href="5.6-multiple-regression-in-r.html#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">2.5</span>, <span class="at">fill=</span><span class="st">&quot;white&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">boundary=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb62-3"><a href="5.6-multiple-regression-in-r.html#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Verbal Ability Grade 1&quot;</span>) <span class="sc">+</span> </span>
<span id="cb62-4"><a href="5.6-multiple-regression-in-r.html#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-5"><a href="5.6-multiple-regression-in-r.html#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="5.6-multiple-regression-in-r.html#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-48-1.png" width="672" />
And the relation between the Grade 2 and Grade 1 verbal ability scores.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="5.6-multiple-regression-in-r.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>verb1, <span class="at">y =</span> verb2)) <span class="sc">+</span> </span>
<span id="cb63-2"><a href="5.6-multiple-regression-in-r.html#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb63-3"><a href="5.6-multiple-regression-in-r.html#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_ellipse</span>(<span class="at">color=</span><span class="st">&quot;blue&quot;</span>, <span class="at">alpha=</span>.<span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="5.6-multiple-regression-in-r.html#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Verbal Ability Grade 1&quot;</span>) <span class="sc">+</span> </span>
<span id="cb63-5"><a href="5.6-multiple-regression-in-r.html#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Verbal Ability Grade 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="5.6-multiple-regression-in-r.html#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">45</span>) <span class="sc">+</span> </span>
<span id="cb63-7"><a href="5.6-multiple-regression-in-r.html#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">45</span>) <span class="sc">+</span></span>
<span id="cb63-8"><a href="5.6-multiple-regression-in-r.html#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-49-1.png" width="672" />
Our regression model becomes
<span class="math display">\[ verb_{2i} = b_01_i + b_1verb_{1i} + \epsilon_{i}\]</span></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="5.6-multiple-regression-in-r.html#cb64-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(verb2 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> verb1,</span>
<span id="cb64-2"><a href="5.6-multiple-regression-in-r.html#cb64-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> wiscsub,</span>
<span id="cb64-3"><a href="5.6-multiple-regression-in-r.html#cb64-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span>
<span id="cb64-4"><a href="5.6-multiple-regression-in-r.html#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = verb2 ~ 1 + verb1, data = wiscsub, na.action = na.exclude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.5305  -3.0362   0.2526   2.7147  12.5020 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 10.62965    1.05164   10.11   &lt;2e-16 ***
## verb1        0.75495    0.05149   14.66   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.261 on 202 degrees of freedom
## Multiple R-squared:  0.5156, Adjusted R-squared:  0.5132 
## F-statistic:   215 on 1 and 202 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>How do we interpret the parameters here?</p>
<p>The intercept, <span class="math inline">\(b_0\)</span>, is the expected value for the outcome variable when all of the predictor variables equal zero. So, we would expect a child to have a Grade 2 verbal score of 10.62965 <em>if</em> they have a Grade 1 verbal score of 0.</p>
<p>The slope, <span class="math inline">\(b_1\)</span> is the expected difference in the outcome variable for each 1-unit difference in the predictor variable. So, <em>across children</em>, for each 1-point difference in a child’s Grade 1 verbal score, we would expect a 0.75495 point difference in the Grade 2 verbal score.</p>
<p>We can plot the relation between ‘verb1’ and ‘verb2,’ and include the predicted line from the analysis.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="5.6-multiple-regression-in-r.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>verb1,<span class="at">y=</span>verb2)) <span class="sc">+</span></span>
<span id="cb66-2"><a href="5.6-multiple-regression-in-r.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">shape=</span><span class="dv">19</span>) <span class="sc">+</span></span>
<span id="cb66-3"><a href="5.6-multiple-regression-in-r.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm,<span class="at">se=</span><span class="cn">TRUE</span>,<span class="at">fullrange=</span><span class="cn">TRUE</span>,<span class="at">colour=</span><span class="st">&quot;red&quot;</span>, <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb66-4"><a href="5.6-multiple-regression-in-r.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span> <span class="st">&quot;Verbal Ability Grade 1&quot;</span>, <span class="at">y=</span> <span class="st">&quot;Verbal Ability Grade 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="5.6-multiple-regression-in-r.html#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="5.6-multiple-regression-in-r.html#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb66-7"><a href="5.6-multiple-regression-in-r.html#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb66-8"><a href="5.6-multiple-regression-in-r.html#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb66-9"><a href="5.6-multiple-regression-in-r.html#cb66-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb66-10"><a href="5.6-multiple-regression-in-r.html#cb66-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb66-11"><a href="5.6-multiple-regression-in-r.html#cb66-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb66-12"><a href="5.6-multiple-regression-in-r.html#cb66-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_blank</span>()</span>
<span id="cb66-13"><a href="5.6-multiple-regression-in-r.html#cb66-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb66-14"><a href="5.6-multiple-regression-in-r.html#cb66-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#draws x and y axis line</span></span>
<span id="cb66-15"><a href="5.6-multiple-regression-in-r.html#cb66-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&#39;black&#39;</span>)) <span class="sc">+</span></span>
<span id="cb66-16"><a href="5.6-multiple-regression-in-r.html#cb66-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#set size of axis labels and titles</span></span>
<span id="cb66-17"><a href="5.6-multiple-regression-in-r.html#cb66-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>),</span>
<span id="cb66-18"><a href="5.6-multiple-regression-in-r.html#cb66-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Note that the lm() is run within the ggplot() + geom_smooth() function. Have to be a bit careful about this as the models get more complicated, but it is very useful for communication.</p>
</div>
<div id="mean-centering-predictors" class="section level3" number="5.6.3">
<h3><span class="header-section-number">5.6.3</span> Mean Centering Predictors</h3>
<p>In this case, and in many other cases, the intercept does not have a ‘useful’ interpretation for the empirical example. This is because no students had a Grade 1 verbal score equal to 0. Therefore, if we want to make the intercept more meaningful, we need to make a Grade 1 verbal score with a more meaningful 0 point. Typically we center the <em>predictor</em> variables in regression analysis. For example, we create a centered variable, <span class="math inline">\(x^{*}_{1i}\)</span> by subtracting the sample mean, <span class="math inline">\(\bar{x_1}\)</span> from each observation,<br />
<span class="math display">\[ x^{*}_{1i} = x_{1i} - \bar{x_1} \]</span>
Our model becomes<br />
<span class="math display">\[ y_i = b_0(1_i) + b_1(x^{*}_{1i}) + \epsilon_i \]</span>
Sample-mean centering <span class="math inline">\(verb_{1i}\)</span>.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="5.6-multiple-regression-in-r.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the mean centered variable</span></span>
<span id="cb68-2"><a href="5.6-multiple-regression-in-r.html#cb68-2" aria-hidden="true" tabindex="-1"></a>wiscsub<span class="sc">$</span>verb1_star <span class="ot">&lt;-</span> wiscsub<span class="sc">$</span>verb1 <span class="sc">-</span> <span class="fu">mean</span>(wiscsub<span class="sc">$</span>verb1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Then we can fit a new model using <span class="math inline">\(verb^{*}_{1i}\)</span>, such that</p>
<p><span class="math display">\[ verb_{2i} = b_0(1_i) + b_1(verb^{*}_{1i}) + \epsilon_i \]</span></p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="5.6-multiple-regression-in-r.html#cb69-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(verb2 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> verb1_star,</span>
<span id="cb69-2"><a href="5.6-multiple-regression-in-r.html#cb69-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> wiscsub,</span>
<span id="cb69-3"><a href="5.6-multiple-regression-in-r.html#cb69-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span>
<span id="cb69-4"><a href="5.6-multiple-regression-in-r.html#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = verb2 ~ 1 + verb1_star, data = wiscsub, na.action = na.exclude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.5305  -3.0362   0.2526   2.7147  12.5020 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 25.41534    0.29831   85.20   &lt;2e-16 ***
## verb1_star   0.75495    0.05149   14.66   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.261 on 202 degrees of freedom
## Multiple R-squared:  0.5156, Adjusted R-squared:  0.5132 
## F-statistic:   215 on 1 and 202 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Note that the estimate for the slope <span class="math inline">\(b_1\)</span> stays the same, but the estimate for the intercept is different. This is because the variable ‘verb1_star’ equals 0 when a child has an average 1st grade verbal score. Therefore the expected value for the 2nd grade verbal score, for <em>a child with an average 1st grade verbal score</em>, is 25.41534.</p>
<p>Let’s plot this:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="5.6-multiple-regression-in-r.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>verb1_star,<span class="at">y=</span>verb2)) <span class="sc">+</span></span>
<span id="cb71-2"><a href="5.6-multiple-regression-in-r.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">shape=</span><span class="dv">19</span>) <span class="sc">+</span></span>
<span id="cb71-3"><a href="5.6-multiple-regression-in-r.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm,<span class="at">se=</span><span class="cn">TRUE</span>,<span class="at">fullrange=</span><span class="cn">TRUE</span>,<span class="at">colour=</span><span class="st">&quot;red&quot;</span>, <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb71-4"><a href="5.6-multiple-regression-in-r.html#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span> <span class="st">&quot;Sample-Centered Verbal Ability Grade 1&quot;</span>, <span class="at">y=</span> <span class="st">&quot;Verbal Ability Grade 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="5.6-multiple-regression-in-r.html#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">20</span>,<span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb71-6"><a href="5.6-multiple-regression-in-r.html#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb71-7"><a href="5.6-multiple-regression-in-r.html#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#theme with white background</span></span>
<span id="cb71-8"><a href="5.6-multiple-regression-in-r.html#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb71-9"><a href="5.6-multiple-regression-in-r.html#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#eliminate background, gridlines, and chart border</span></span>
<span id="cb71-10"><a href="5.6-multiple-regression-in-r.html#cb71-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb71-11"><a href="5.6-multiple-regression-in-r.html#cb71-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_blank</span>()</span>
<span id="cb71-12"><a href="5.6-multiple-regression-in-r.html#cb71-12" aria-hidden="true" tabindex="-1"></a>    ,<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>()</span>
<span id="cb71-13"><a href="5.6-multiple-regression-in-r.html#cb71-13" aria-hidden="true" tabindex="-1"></a>    ,<span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb71-14"><a href="5.6-multiple-regression-in-r.html#cb71-14" aria-hidden="true" tabindex="-1"></a>    ,<span class="at">panel.border =</span> <span class="fu">element_blank</span>()</span>
<span id="cb71-15"><a href="5.6-multiple-regression-in-r.html#cb71-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb71-16"><a href="5.6-multiple-regression-in-r.html#cb71-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#draws x and y axis line</span></span>
<span id="cb71-17"><a href="5.6-multiple-regression-in-r.html#cb71-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&#39;black&#39;</span>)) <span class="sc">+</span></span>
<span id="cb71-18"><a href="5.6-multiple-regression-in-r.html#cb71-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#set size of axis labels and titles</span></span>
<span id="cb71-19"><a href="5.6-multiple-regression-in-r.html#cb71-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>),</span>
<span id="cb71-20"><a href="5.6-multiple-regression-in-r.html#cb71-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>Note the change of scale on the x-axis.</p>
</div>
<div id="multiple-linear-regression" class="section level3" number="5.6.4">
<h3><span class="header-section-number">5.6.4</span> Multiple Linear Regression</h3>
<p>Now, let’s include a second predictor. We have information on the number of years of education for the children’s mothers, variable <code>momed</code>. The values in <code>momed</code> indicate the number of years of education each mother completed. First, let’s take a look at the distribution of this new predictor variable.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="5.6-multiple-regression-in-r.html#cb73-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(wiscsub<span class="sc">$</span>momed)</span></code></pre></div>
<pre><code>##    vars   n  mean  sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 204 10.81 2.7   11.5      11 2.97 5.5  18  12.5 -0.36     0.01 0.19</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="5.6-multiple-regression-in-r.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>momed)) <span class="sc">+</span> </span>
<span id="cb75-2"><a href="5.6-multiple-regression-in-r.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">2.5</span>, <span class="at">fill=</span><span class="st">&quot;white&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb75-3"><a href="5.6-multiple-regression-in-r.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="5.6-multiple-regression-in-r.html#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Years of Mother&#39;s Education&quot;</span>) <span class="sc">+</span> </span>
<span id="cb75-5"><a href="5.6-multiple-regression-in-r.html#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb75-6"><a href="5.6-multiple-regression-in-r.html#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_bar).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="672" />
And the relation between Grade 2 verbal scores and momed.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="5.6-multiple-regression-in-r.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, <span class="fu">aes</span>(<span class="at">x=</span>momed, <span class="at">y =</span> verb2)) <span class="sc">+</span> </span>
<span id="cb77-2"><a href="5.6-multiple-regression-in-r.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb77-3"><a href="5.6-multiple-regression-in-r.html#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">20</span>) <span class="sc">+</span> </span>
<span id="cb77-4"><a href="5.6-multiple-regression-in-r.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb77-5"><a href="5.6-multiple-regression-in-r.html#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Mother&#39;s Education (Years)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Verbal Ability Grade 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-6"><a href="5.6-multiple-regression-in-r.html#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Our model now becomes</p>
<p><span class="math display">\[ verb_{2i} = b_01_{i} + b_1verb^{*}_{1i} + b_2momed^{*}_{i} + \epsilon_{i}\]</span></p>
<p>where <span class="math inline">\(verb^{*}_{1i}\)</span> is the sample-centered version of <span class="math inline">\(verb_{1i}\)</span>, and <span class="math inline">\(momed^{*}_{i}\)</span> is the sample-centered version of <span class="math inline">\(momed_{i}\)</span> – again, this makes things easier to interpret. The slope, <span class="math inline">\(b_2\)</span> is the expected difference in grade 2 verbal score for each 1 year difference in the mom’s education.</p>
<p>Calculate centered momed variable.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="5.6-multiple-regression-in-r.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean-centered version of mother&#39;s education variable</span></span>
<span id="cb78-2"><a href="5.6-multiple-regression-in-r.html#cb78-2" aria-hidden="true" tabindex="-1"></a>wiscsub<span class="sc">$</span>momed_star <span class="ot">&lt;-</span> wiscsub<span class="sc">$</span>momed <span class="sc">-</span> <span class="fu">mean</span>(wiscsub<span class="sc">$</span>momed)</span></code></pre></div>
<p>Fit model to the data.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="5.6-multiple-regression-in-r.html#cb79-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(verb2 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> verb1_star <span class="sc">+</span> momed_star,</span>
<span id="cb79-2"><a href="5.6-multiple-regression-in-r.html#cb79-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> wiscsub,</span>
<span id="cb79-3"><a href="5.6-multiple-regression-in-r.html#cb79-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span>
<span id="cb79-4"><a href="5.6-multiple-regression-in-r.html#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = verb2 ~ 1 + verb1_star + momed_star, data = wiscsub, 
##     na.action = na.exclude)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.4354 -2.9189 -0.1542  2.3746 11.1678 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 25.41534    0.29069  87.430  &lt; 2e-16 ***
## verb1_star   0.66786    0.05626  11.872  &lt; 2e-16 ***
## momed_star   0.41454    0.12108   3.424 0.000749 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.152 on 201 degrees of freedom
## Multiple R-squared:  0.5422, Adjusted R-squared:  0.5377 
## F-statistic: 119.1 on 2 and 201 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now we have an intercept and two slopes.</p>
<p><span class="math inline">\(b_0\)</span> is the expected value of the outcome variable when all other variables are 0. Therefore, in this case, <span class="math inline">\(b_0\)</span> is the expected Grade 2 verbal score for a child with an average Grade 1 verbal score (i.e. <span class="math inline">\(verb^{*}_{1i}\)</span> = 0) <em>and</em> whose mother had an average education (i.e. <span class="math inline">\(momed^{*}_{i}\)</span> = 0, <span class="math inline">\(\bar{momed_{i}}\)</span> = 10.81 years of education.</p>
<p><span class="math inline">\(b_1\)</span> is the expected difference in the outcome for a 1-unit difference in <span class="math inline">\(x_{1i}\)</span>. In this example (i.e. ‘model4’), <span class="math inline">\(b_1\)</span> is the expected difference in Grade 2 verbal score (outcome variable, <span class="math inline">\(y_i\)</span> = <span class="math inline">\(verb_{2i}\)</span>) for a 1 point difference in the Grade 1 verbal score (<span class="math inline">\(x_{1i}\)</span> = <span class="math inline">\(verb^{*}_{1i}\)</span>), assuming average level of mother’s education.</p>
<p><span class="math inline">\(b_2\)</span> is the expected difference in the outcome for a 1-unit difference in <span class="math inline">\(x_{2i}\)</span>. For this example (i.e. ‘model4’), <span class="math inline">\(b_2\)</span> is the expected difference in Grade 2 verbal score (outcome variable, <span class="math inline">\(y_i\)</span> = <span class="math inline">\(verb_{2i}\)</span>) for each year difference in mother’s education (<span class="math inline">\(x_{2i}\)</span> = <span class="math inline">\(momed^{*}_i\)</span>).</p>
<p>To better understand the implied relation between <span class="math inline">\(verb_{2i}\)</span>, <span class="math inline">\(verb^{*}_{1i}\)</span>, and <span class="math inline">\(momed^{*}_i\)</span>, we can plot the predicted values implied by the model. This will be a 3-dimensional plot because we are interested in the relations among three variables: <span class="math inline">\(\left\{verb_{2i}, verb^{*}_{1i}, momed^{*}_{i}\right\}\)</span></p>
<p>To make a 3-d plot, we create a matrix of the ‘decision space.’ The rows correspond to levels of one predictor variable <span class="math inline">\((verb^{*}_{1i})\)</span>, the columns of the other predictor variable <span class="math inline">\((momed^{*}_{i})\)</span>, and the value at the intersections is the predicted value of <span class="math inline">\(verb_{2i}\)</span>.</p>
<p>The range of observed values of <span class="math inline">\((momed^{*}_{i})\)</span> is [-5, 7], and the range of observed values of <span class="math inline">\((verb^{*}_{1i})\)</span> is [-15, 16]. This implies a 32 row (for the integer values of <span class="math inline">\((verb^{*}_{1i})\)</span>) by 13 columns (for the integer values of <span class="math inline">\((momed^{*}_{i})\)</span>) matrix decision space.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="5.6-multiple-regression-in-r.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create an empty matrix for the predicted scores</span></span>
<span id="cb81-2"><a href="5.6-multiple-regression-in-r.html#cb81-2" aria-hidden="true" tabindex="-1"></a>pred_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">32</span>, <span class="at">ncol =</span> <span class="dv">13</span>)</span>
<span id="cb81-3"><a href="5.6-multiple-regression-in-r.html#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="5.6-multiple-regression-in-r.html#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co">#fill in all the cells of the matrix </span></span>
<span id="cb81-5"><a href="5.6-multiple-regression-in-r.html#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(momed <span class="cf">in</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>)){</span>
<span id="cb81-6"><a href="5.6-multiple-regression-in-r.html#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span>(verb <span class="cf">in</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">15</span><span class="sc">:</span><span class="dv">16</span>)){</span>
<span id="cb81-7"><a href="5.6-multiple-regression-in-r.html#cb81-7" aria-hidden="true" tabindex="-1"></a>        curr_row <span class="ot">&lt;-</span> verb <span class="sc">+</span> <span class="dv">16</span> <span class="co"># the index should start at 1, shifting here</span></span>
<span id="cb81-8"><a href="5.6-multiple-regression-in-r.html#cb81-8" aria-hidden="true" tabindex="-1"></a>        curr_col <span class="ot">&lt;-</span> momed <span class="sc">+</span> <span class="dv">6</span></span>
<span id="cb81-9"><a href="5.6-multiple-regression-in-r.html#cb81-9" aria-hidden="true" tabindex="-1"></a>        <span class="co">#prediction equation</span></span>
<span id="cb81-10"><a href="5.6-multiple-regression-in-r.html#cb81-10" aria-hidden="true" tabindex="-1"></a>        pred_matrix[curr_row, curr_col] <span class="ot">=</span> <span class="fl">25.41534</span> <span class="sc">+</span> <span class="fl">0.66786</span><span class="sc">*</span>(verb) <span class="sc">+</span> <span class="fl">0.41454</span><span class="sc">*</span>(momed)</span>
<span id="cb81-11"><a href="5.6-multiple-regression-in-r.html#cb81-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb81-12"><a href="5.6-multiple-regression-in-r.html#cb81-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb81-13"><a href="5.6-multiple-regression-in-r.html#cb81-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-14"><a href="5.6-multiple-regression-in-r.html#cb81-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Making 3-d perspective plot</span></span>
<span id="cb81-15"><a href="5.6-multiple-regression-in-r.html#cb81-15" aria-hidden="true" tabindex="-1"></a><span class="fu">persp</span>(<span class="at">x =</span> <span class="sc">-</span><span class="dv">15</span><span class="sc">:</span><span class="dv">16</span>, <span class="at">y =</span> <span class="sc">-</span><span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>, <span class="at">z =</span> pred_matrix,</span>
<span id="cb81-16"><a href="5.6-multiple-regression-in-r.html#cb81-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">shade=</span>.<span class="dv">7</span>, <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">expand =</span> .<span class="dv">5</span>,</span>
<span id="cb81-17"><a href="5.6-multiple-regression-in-r.html#cb81-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab=</span><span class="st">&quot;Grade 1 Verbal &quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Years of Mom Ed&quot;</span>,<span class="at">zlab=</span><span class="st">&quot;Grade 2 Verbal&quot;</span>,</span>
<span id="cb81-18"><a href="5.6-multiple-regression-in-r.html#cb81-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;Prediction Surface for Grade 2 Verbal&quot;</span>,</span>
<span id="cb81-19"><a href="5.6-multiple-regression-in-r.html#cb81-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">theta=</span><span class="sc">-</span><span class="dv">30</span>,<span class="at">phi=</span><span class="dv">30</span>,<span class="at">d=</span><span class="dv">5</span>) <span class="co"># this part defines the viewing direction, theta and phi are angles</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" />
Along the right face of the cube one can see the linear relation between Grade 1 verbal score and Grade 2 verbal score. Along the left face one can see the linear relation between years of mother’s education and Grade 2 verbal score. The surface of the plane indicates how the two variables contribute to the Grade 2 verbal scores.</p>
</div>
<div id="interactions" class="section level3" number="5.6.5">
<h3><span class="header-section-number">5.6.5</span> Interactions</h3>
<p>Ok, let’s move on to the topic of an ‘interaction’ which uses the product of two predictor variables as a new predictor.</p>
<p>Working up a slightly different example with the ‘grad’ variable (whether mom graduated high school),</p>
<p><span class="math display">\[ verb_{2i} = b_0(1_i) + b_1(verb^{*}_{1i}) + b_2(grad_{i}) + b_3(verb^{*}_{1i})(grad_{i}) + \epsilon_{i}\]</span></p>
<p>Where <span class="math inline">\(verb^{*}_{1i}\)</span> is the mean-centered version of <span class="math inline">\(verb_{1i}\)</span>, and <span class="math inline">\(grad_i\)</span> is a dummy coded variable that equals 0 if the child’s mother <em>did not</em> graduate high school, and equals 1 if the child’s mother <em>did</em> graduate high school.</p>
<p>We did not sample-mean center <span class="math inline">\(grad_i\)</span> in this example because a value of 0 already has substantive meaning for the current example (i.e. when <span class="math inline">\(grad_i\)</span> equals 0, the mother <em>did not</em> graduate high school).</p>
<p>Often, we describe phenomena in terms of <em>moderation</em>; or that the relation between two variables (i.e. <span class="math inline">\(y_i\)</span> and <span class="math inline">\(x_{1i}\)</span>) is <em>moderated</em> by a third variable (i.e. <span class="math inline">\(x_{2i}\)</span>). For example, the relation between Grade 1 and Grade 2 verbal scores may be <em>moderated</em> by mother’s graduation status. More specifically, the relation between 1st and 2nd grade verbal score may be different for children whose mothers’ did not or did graduate from high school.</p>
<p>The inclusion of product terms (i.e. interactions) allows for a direct investigation of a <em>moderation</em> hypothesis.</p>
<p>When we use a product term, we should define one of the variables as the moderator and one of the variables as the predictor of interest. Let’s call <span class="math inline">\(verb^{*}_{1i}\)</span> the predictor of interest, and <span class="math inline">\(grad_{i}\)</span> the moderator. When the moderator is a dummy variable then the form of the moderation becomes fairly simple; we will have one equation for <span class="math inline">\(grad_{i} = 0\)</span>, and a second equation for <span class="math inline">\(grad_i = 1\)</span>. To illustrate the notion of two equations, let’s rewrite the regression equation</p>
<p><span class="math display">\[ verb_{2i} = b_0(1_i) + b_1(verb^{*}_{1i}) + b_2(grad_{i}) + b_3(verb^{*}_{1i})(grad_{i}) + \epsilon_{i}\]</span>
as
<span class="math display">\[ verb_{2i} = [b_0(1_i) + b_2(grad_{i})] + [b_1 +  b_3(grad_{i})](verb^{*}_{1i}) + \epsilon_{i}\]</span></p>
<p>Then, we insert the two possible values for <span class="math inline">\(grad_i\)</span>. For example, if <span class="math inline">\(grad_i = 0\)</span> , then the equation simplifies to</p>
<p><span class="math display">\[ verb_{2i} = [b_0](1_i) + [b_1](verb^{*}_{1i}) + \epsilon_{i}\]</span></p>
<p>Please note that the equation above represents the relation between <span class="math inline">\(verb_{2i}\)</span> and <span class="math inline">\(verb^{*}_{1i}\)</span> <em>for children whose mother’s did not graduate high school</em>. Therefore, we can interpret the parameter estimates <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> with respect to those children. More specifically, the expected Grade 2 verbal score for a child whose mother did not graduate high school <em>and</em> who had an average Grade 1 verbal score is <span class="math inline">\(b_0\)</span>. Also, for a child whose mother did not graduate high school, <span class="math inline">\(b_1\)</span> is the expected difference in their Grade 2 verbal score for a one-point difference in their Grade 1 verbal score.</p>
<p>Now, we return to the original equation and insert <span class="math inline">\(grad_i = 1\)</span> in order to make meaning out of <span class="math inline">\(b_2\)</span> and <span class="math inline">\(b_3\)</span>. If <span class="math inline">\(grad_i = 1\)</span>, then we have</p>
<p><span class="math display">\[ verb_{2i} = [b_0(1_i) + b_2(1)] + [(b_1 +  b_3(1))](verb^{*}_{1i}) + \epsilon_{i}\]</span></p>
<p>This new equation above represents the relation between <span class="math inline">\(verb_{2i}\)</span> and <span class="math inline">\(verb^{*}_{1i}\)</span> <em>for children whose mother’s did graduate high school</em>. The parameter estimates <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> maintain their interpretation from before. But now each of them is <em>moderated</em> (i.e. shifted or altered) by <span class="math inline">\(b_2\)</span> or <span class="math inline">\(b_3\)</span>.</p>
<p>Specifically, the expected Grade 2 verbal score for a child whose mother did graduate high school <em>and</em> who earned an average Grade 1 verbal score is <span class="math inline">\(b_0 + b_2\)</span>. And, for a child whose mother did graduate high school, <span class="math inline">\(b_1 + b_3\)</span> is the expected difference in their Grade 2 verbal score for a one-point change in their Grade 1 verbal score.</p>
<p>OK - let’s fit the model! Note that within this model we use the code ‘I(verb1_star * grad).’ This produces the interaction term within the model. The wrapper function ‘I()’ indicates to R to perform this data computation as-is, otherwise we would need to perform this computation (i.e. the multiplication of ‘verb1_star’ by ‘grad’) outside of the function lm(). A word of caution, the model may run without I() used, but it may not give you back the intended result. Therefore, it is best practice to use the I() function to be explicit about what variables are multiplied together to form the interaction.
Alternatively, one can also use the code ‘verb1_star:grad’ (with the colon). Be careful of the assumptions made by the lm() function. Always check that the output makes sense in relation to the intended model.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="5.6-multiple-regression-in-r.html#cb82-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(verb2 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> verb1_star <span class="sc">+</span> grad <span class="sc">+</span> <span class="fu">I</span>(verb1_star<span class="sc">*</span>grad),</span>
<span id="cb82-2"><a href="5.6-multiple-regression-in-r.html#cb82-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> wiscsub,</span>
<span id="cb82-3"><a href="5.6-multiple-regression-in-r.html#cb82-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span>
<span id="cb82-4"><a href="5.6-multiple-regression-in-r.html#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = verb2 ~ 1 + verb1_star + grad + I(verb1_star * grad), 
##     data = wiscsub, na.action = na.exclude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.3433  -3.0761  -0.0825   2.5689  10.7289 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           25.2663     0.3416  73.956   &lt;2e-16 ***
## verb1_star             0.7861     0.0604  13.015   &lt;2e-16 ***
## grad                   1.4632     0.8107   1.805   0.0726 .  
## I(verb1_star * grad)  -0.2430     0.1324  -1.836   0.0678 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.232 on 200 degrees of freedom
## Multiple R-squared:  0.5268, Adjusted R-squared:  0.5197 
## F-statistic: 74.22 on 3 and 200 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="5.6-multiple-regression-in-r.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Alternative formula </span></span>
<span id="cb84-2"><a href="5.6-multiple-regression-in-r.html#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model5 &lt;- lm(verb2 ~ 1 + verb1_star + grad + verb1_star:grad,</span></span>
<span id="cb84-3"><a href="5.6-multiple-regression-in-r.html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="co">#               data = wiscsub,</span></span>
<span id="cb84-4"><a href="5.6-multiple-regression-in-r.html#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co">#               na.action = na.exclude)</span></span>
<span id="cb84-5"><a href="5.6-multiple-regression-in-r.html#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(model5)</span></span></code></pre></div>
<p>The parameter estimates from this model indicate that, for children whose mother did not graduate high school, the expected Grade 2 verbal score for a child that earned an average 1st grade verbal score equals 25.2663 (<span class="math inline">\(b_0\)</span>). Also, for children whose mother did not graduate high school, a 1-point difference in their Grade 1 verbal score is expected to correspond with a 0.7861 (<span class="math inline">\(b_1\)</span>) point difference in the Grade 2 verbal score.</p>
<p>Moreover, the parameter estimates indicate that, for children whose mother did graduate high school, the expected Grade 2 verbal score for a child that earned an average Grade 1 verbal score is 25.2663 + 1.4632 = 26.7295 (<span class="math inline">\(b_0 + b_2\)</span>). Also, for children whose mother graduated high school, a 1-point difference in their Grade 1 verbal score is expected to correspond with a (<span class="math inline">\(b_1 + b_3\)</span>) = 0.7861 - 0.2430 = 0.5431 point difference in the Grade 2 verbal score.</p>
<p>Even though the interaction is not significant, we can plot it for illustrating the moderation effect:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="5.6-multiple-regression-in-r.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot of moderation</span></span>
<span id="cb85-2"><a href="5.6-multiple-regression-in-r.html#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub, </span>
<span id="cb85-3"><a href="5.6-multiple-regression-in-r.html#cb85-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>verb2,<span class="at">y=</span>verb1_star, <span class="at">color =</span> <span class="fu">factor</span>(grad))) <span class="sc">+</span></span>
<span id="cb85-4"><a href="5.6-multiple-regression-in-r.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb85-5"><a href="5.6-multiple-regression-in-r.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>, <span class="at">se=</span><span class="cn">TRUE</span>, <span class="at">fullrange=</span><span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb85-6"><a href="5.6-multiple-regression-in-r.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;1st Grade Verbal Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb85-7"><a href="5.6-multiple-regression-in-r.html#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;2nd Grade Verbal Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb85-8"><a href="5.6-multiple-regression-in-r.html#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="st">&quot;HS Grad&quot;</span>)) <span class="sc">+</span></span>
<span id="cb85-9"><a href="5.6-multiple-regression-in-r.html#cb85-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>The example from ‘model5’ contained an interaction using a dummy variable (i.e., <span class="math inline">\(grad_i\)</span>). Interactions may also occur between two continuous variables (i.e., <span class="math inline">\(verb^{*}_{1i}\)</span> and <span class="math inline">\(momed^{*}_{i}\)</span>). We will not cover here, but note that it is still very useful to consider and communicate those interactions as <em>moderation</em>. There are many resources on interactions of two (or more) continuous variables.</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Fox, John, and Sanford Weisberg. 2019. <em>An <span>R</span> Companion to Applied Regression</em>. Third. Thousand Oaks <span>CA</span>: Sage. <a href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/">https://socialsciences.mcmaster.ca/jfox/Books/Companion/</a>.
</div>
<div class="csl-entry">
McArdle, J. J. 1988. <span>“Dynamic but Structural Equation Modeling of Repeated Measures Data.”</span> In <em>Handbook of Multivariate Experimental Psychology, 2nd Ed</em>, 561–614. Perspectives on Individual Differences. <span>New York, NY, US</span>: <span>Plenum Press</span>. <a href="https://doi.org/10.1007/978-1-4613-0893-5_17">https://doi.org/10.1007/978-1-4613-0893-5_17</a>.
</div>
<div class="csl-entry">
Mcardle, J. J., and MARK S. Aber. 1990. <span>“Chapter 5 - <span>Patterns</span> of <span>Change</span> Within <span>Latent Variable Structural Equation Models</span>.”</span> In <em>Statistical <span>Methods</span> in <span>Longitudinal Research</span></em>, edited by Alexander von Eye, 1:151–224. Statistical <span>Modeling</span> and <span>Decision Science</span>. <span>San Diego</span>: <span>Academic Press</span>. <a href="https://doi.org/10.1016/B978-0-12-724960-5.50010-X">https://doi.org/10.1016/B978-0-12-724960-5.50010-X</a>.
</div>
<div class="csl-entry">
McArdle, J. J., and David Epstein. 1987. <span>“Latent Growth Curves Within Developmental Structural Equation Models.”</span> <em>Child Development</em> 58 (1): 110–33. <a href="https://doi.org/10.2307/1130295">https://doi.org/10.2307/1130295</a>.
</div>
<div class="csl-entry">
McArdle, J. J., and John R. Nesselroade. 1994. <span>“Using Multivariate Data to Structure Developmental Change.”</span> In <em>Life-Span Developmental Psychology: <span>Methodological</span> Contributions</em>, 223–67. The <span>West Virginia University</span> Conferences on Life-Span Developmental Psychology. <span>Hillsdale, NJ, US</span>: <span>Lawrence Erlbaum Associates, Inc</span>.
</div>
<div class="csl-entry">
Osborne, R. T., and D. E. Suddick. 1972. <span>“A Longitudinal Investigation of the Intellectual Differentiation Hypothesis.”</span> <em>The Journal of Genetic Psychology: Research and Theory on Human Development</em> 121 (1): 83–89. <a href="https://doi.org/10.1080/00221325.1972.10533131">https://doi.org/10.1080/00221325.1972.10533131</a>.
</div>
<div class="csl-entry">
Revelle, William. 2021. <em>Psych: Procedures for Psychological, Psychometric, and Personality Research</em>. Evanston, Illinois: Northwestern University. <a href="https://CRAN.R-project.org/package=psych">https://CRAN.R-project.org/package=psych</a>.
</div>
<div class="csl-entry">
Tierney, Nicholas, Di Cook, Miles McBain, and Colin Fay. 2021. <em>Naniar: Data Structures, Summaries, and Visualisations for Missing Data</em>. <a href="https://CRAN.R-project.org/package=naniar">https://CRAN.R-project.org/package=naniar</a>.
</div>
<div class="csl-entry">
Wechsler, David. 1949. <em>Wechsler <span>Intelligence Scale</span> for <span>Children</span></em>. Wechsler <span>Intelligence Scale</span> for <span>Children</span>. <span>San Antonio, TX, US</span>: <span>Psychological Corporation</span>.
</div>
<div class="csl-entry">
Wickham, Hadley. 2016. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div class="csl-entry">
———. 2021. <em>Tidyr: Tidy Messy Data</em>. <a href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a>.
</div>
</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="5.5-example-data-2.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/zackfisher/HDFS523/edit/master/05_linear_regression.Rmd",
"text": "Suggest an edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
