<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.5 Logistic Regression: Empirical example with a Binomial (Bernoulli, binary) distributed outcome variable | HDFS 523: Strategies for Data Analysis in Developmental Research</title>
  <meta name="description" content="Course notes for HDFS 523" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="7.5 Logistic Regression: Empirical example with a Binomial (Bernoulli, binary) distributed outcome variable | HDFS 523: Strategies for Data Analysis in Developmental Research" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/image1.png" />
  <meta property="og:description" content="Course notes for HDFS 523" />
  <meta name="github-repo" content="zackfisher/HDFS523" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.5 Logistic Regression: Empirical example with a Binomial (Bernoulli, binary) distributed outcome variable | HDFS 523: Strategies for Data Analysis in Developmental Research" />
  
  <meta name="twitter:description" content="Course notes for HDFS 523" />
  <meta name="twitter:image" content="/images/image1.png" />

<meta name="author" content="Zachary F. Fisher" />


<meta name="date" content="2022-01-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="null" type="image/x-icon" />
<link rel="prev" href="7.4-binary-outcomes.html"/>
<link rel="next" href="7.6-count-outcomes.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course notes for HDFS 523</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About This Book</a>
<ul>
<li class="chapter" data-level="1.1" data-path="1.1-why-this-book.html"><a href="1.1-why-this-book.html"><i class="fa fa-check"></i><b>1.1</b> Why this book?</a></li>
<li class="chapter" data-level="1.2" data-path="1.2-code-folding.html"><a href="1.2-code-folding.html"><i class="fa fa-check"></i><b>1.2</b> Code Folding</a></li>
<li class="chapter" data-level="1.3" data-path="1.3-acknowledgements.html"><a href="1.3-acknowledgements.html"><i class="fa fa-check"></i><b>1.3</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-chapter-2.html"><a href="2-chapter-2.html"><i class="fa fa-check"></i><b>2</b> Data Cleaning</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2.1-example-data.html"><a href="2.1-example-data.html"><i class="fa fa-check"></i><b>2.1</b> Example Data</a></li>
<li class="chapter" data-level="2.2" data-path="2.2-reading-in-repeated-measures-data.html"><a href="2.2-reading-in-repeated-measures-data.html"><i class="fa fa-check"></i><b>2.2</b> Reading in Repeated Measures Data</a></li>
<li class="chapter" data-level="2.3" data-path="2.3-familiarize-yourself-with-the-data.html"><a href="2.3-familiarize-yourself-with-the-data.html"><i class="fa fa-check"></i><b>2.3</b> Familiarize Yourself with the Data</a></li>
<li class="chapter" data-level="2.4" data-path="2.4-look-for-duplicated-ids.html"><a href="2.4-look-for-duplicated-ids.html"><i class="fa fa-check"></i><b>2.4</b> Look for Duplicated IDs</a></li>
<li class="chapter" data-level="2.5" data-path="2.5-using-table-to-spot-irregularities.html"><a href="2.5-using-table-to-spot-irregularities.html"><i class="fa fa-check"></i><b>2.5</b> Using <code>table()</code> to Spot Irregularities</a></li>
<li class="chapter" data-level="2.6" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html"><i class="fa fa-check"></i><b>2.6</b> Missing Data</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#generating-example-data"><i class="fa fa-check"></i><b>2.6.1</b> Generating Example Data</a></li>
<li class="chapter" data-level="2.6.2" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#recoding-values-with-na"><i class="fa fa-check"></i><b>2.6.2</b> Recoding Values with <code>NA</code></a></li>
<li class="chapter" data-level="2.6.3" data-path="2.6-missing-data.html"><a href="2.6-missing-data.html#missing-data-visualization"><i class="fa fa-check"></i><b>2.6.3</b> Missing Data Visualization</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="2.7-exporting-data.html"><a href="2.7-exporting-data.html"><i class="fa fa-check"></i><b>2.7</b> Exporting Data</a></li>
<li class="chapter" data-level="2.8" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html"><i class="fa fa-check"></i><b>2.8</b> Reshaping Repeated Measures Data</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html#reshape-wide-to-long"><i class="fa fa-check"></i><b>2.8.1</b> Reshape Wide to Long</a></li>
<li class="chapter" data-level="2.8.2" data-path="2.8-reshaping-repeated-measures-data.html"><a href="2.8-reshaping-repeated-measures-data.html#reshape-long-to-wide"><i class="fa fa-check"></i><b>2.8.2</b> Reshape Long to Wide</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-chapter-3.html"><a href="3-chapter-3.html"><i class="fa fa-check"></i><b>3</b> Describing Longitudinal Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3.1-example-data-1.html"><a href="3.1-example-data-1.html"><i class="fa fa-check"></i><b>3.1</b> Example Data</a></li>
<li class="chapter" data-level="3.2" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html"><i class="fa fa-check"></i><b>3.2</b> Describing Means and Variances</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html#verbal-ability-all-persons-and-occasions"><i class="fa fa-check"></i><b>3.2.1</b> Verbal Ability (All Persons and Occasions)</a></li>
<li class="chapter" data-level="3.2.2" data-path="3.2-describing-means-and-variances.html"><a href="3.2-describing-means-and-variances.html#verbal-ability-across-time"><i class="fa fa-check"></i><b>3.2.2</b> Verbal Ability (Across Time)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="3.3-describing-covariances.html"><a href="3.3-describing-covariances.html"><i class="fa fa-check"></i><b>3.3</b> Describing Covariances</a></li>
<li class="chapter" data-level="3.4" data-path="3.4-individual-level-descriptives.html"><a href="3.4-individual-level-descriptives.html"><i class="fa fa-check"></i><b>3.4</b> Individual-Level Descriptives</a></li>
<li class="chapter" data-level="3.5" data-path="3.5-references.html"><a href="3.5-references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-chapter-4.html"><a href="4-chapter-4.html"><i class="fa fa-check"></i><b>4</b> Matrix Algebra Review</a>
<ul>
<li class="chapter" data-level="4.1" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html"><i class="fa fa-check"></i><b>4.1</b> Types of matrices</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#square"><i class="fa fa-check"></i><b>4.1.1</b> Square</a></li>
<li class="chapter" data-level="4.1.2" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#symmetric"><i class="fa fa-check"></i><b>4.1.2</b> Symmetric</a></li>
<li class="chapter" data-level="4.1.3" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#diagonal"><i class="fa fa-check"></i><b>4.1.3</b> Diagonal</a></li>
<li class="chapter" data-level="4.1.4" data-path="4.1-types-of-matrices.html"><a href="4.1-types-of-matrices.html#identity"><i class="fa fa-check"></i><b>4.1.4</b> Identity</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html"><i class="fa fa-check"></i><b>4.2</b> Operations on Matrices</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-transpose"><i class="fa fa-check"></i><b>4.2.1</b> Matrix Transpose</a></li>
<li class="chapter" data-level="4.2.2" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-trace"><i class="fa fa-check"></i><b>4.2.2</b> Matrix Trace</a></li>
<li class="chapter" data-level="4.2.3" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#addition"><i class="fa fa-check"></i><b>4.2.3</b> Addition</a></li>
<li class="chapter" data-level="4.2.4" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#subtraction"><i class="fa fa-check"></i><b>4.2.4</b> Subtraction</a></li>
<li class="chapter" data-level="4.2.5" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-multiplication"><i class="fa fa-check"></i><b>4.2.5</b> Matrix Multiplication</a></li>
<li class="chapter" data-level="4.2.6" data-path="4.2-operations-on-matrices.html"><a href="4.2-operations-on-matrices.html#matrix-division"><i class="fa fa-check"></i><b>4.2.6</b> Matrix Division</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-chapter-5.html"><a href="5-chapter-5.html"><i class="fa fa-check"></i><b>5</b> Ordinary Least Squares Review</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5.1-linear-regression-model.html"><a href="5.1-linear-regression-model.html"><i class="fa fa-check"></i><b>5.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="5.2" data-path="5.2-ordinary-least-squares-ols.html"><a href="5.2-ordinary-least-squares-ols.html"><i class="fa fa-check"></i><b>5.2</b> Ordinary Least Squares (OLS)</a></li>
<li class="chapter" data-level="5.3" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html"><i class="fa fa-check"></i><b>5.3</b> Assumptions of OLS</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html#assumption-1.-mathbbeepsilon_i-0"><i class="fa fa-check"></i><b>5.3.1</b> Assumption 1. <span class="math inline">\(\mathbb{E}(\epsilon_{i}) = 0\)</span></a></li>
<li class="chapter" data-level="5.3.2" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html#assumption-2.-homoscedasticity"><i class="fa fa-check"></i><b>5.3.2</b> Assumption 2. Homoscedasticity</a></li>
<li class="chapter" data-level="5.3.3" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html#mathbbeepsilon_iepsilon_j-0"><i class="fa fa-check"></i><b>5.3.3</b> 3. <span class="math inline">\(\mathbb{E}(\epsilon_{i}\epsilon_{j}) = 0\)</span></a></li>
<li class="chapter" data-level="5.3.4" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html#no-perfect-collinearity"><i class="fa fa-check"></i><b>5.3.4</b> 4. No Perfect Collinearity</a></li>
<li class="chapter" data-level="5.3.5" data-path="5.3-assumptions-of-ols.html"><a href="5.3-assumptions-of-ols.html#mathbbcepsilon_ix_ki-0"><i class="fa fa-check"></i><b>5.3.5</b> 5. <span class="math inline">\(\mathbb{C}(\epsilon_{i},x_{ki}) = 0\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5.4-properties-of-the-ols-estimator.html"><a href="5.4-properties-of-the-ols-estimator.html"><i class="fa fa-check"></i><b>5.4</b> Properties of the OLS Estimator</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="5.4-properties-of-the-ols-estimator.html"><a href="5.4-properties-of-the-ols-estimator.html#consistentcy-of-boldsymbolbeta"><i class="fa fa-check"></i><b>5.4.1</b> 1. Consistentcy of <span class="math inline">\(\boldsymbol{{\beta}}\)</span></a></li>
<li class="chapter" data-level="5.4.2" data-path="5.4-properties-of-the-ols-estimator.html"><a href="5.4-properties-of-the-ols-estimator.html#asymptotic-normality"><i class="fa fa-check"></i><b>5.4.2</b> 2. Asymptotic Normality</a></li>
<li class="chapter" data-level="5.4.3" data-path="5.4-properties-of-the-ols-estimator.html"><a href="5.4-properties-of-the-ols-estimator.html#variance-of-hatbeta"><i class="fa fa-check"></i><b>5.4.3</b> Variance of <span class="math inline">\(\hat{\beta}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5.5-failure-to-meet-assumptions.html"><a href="5.5-failure-to-meet-assumptions.html"><i class="fa fa-check"></i><b>5.5</b> Failure to Meet Assumptions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="5.5-failure-to-meet-assumptions.html"><a href="5.5-failure-to-meet-assumptions.html#failure-of-assumption-1."><i class="fa fa-check"></i><b>5.5.1</b> Failure of Assumption 1.</a></li>
<li class="chapter" data-level="5.5.2" data-path="5.5-failure-to-meet-assumptions.html"><a href="5.5-failure-to-meet-assumptions.html#failure-of-assumption-2-or-3."><i class="fa fa-check"></i><b>5.5.2</b> Failure of Assumption 2 or 3.</a></li>
<li class="chapter" data-level="5.5.3" data-path="5.5-failure-to-meet-assumptions.html"><a href="5.5-failure-to-meet-assumptions.html#failure-of-assumption-5."><i class="fa fa-check"></i><b>5.5.3</b> Failure of Assumption 5.</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="5.6-regression-and-matrix-notation.html"><a href="5.6-regression-and-matrix-notation.html"><i class="fa fa-check"></i><b>5.6</b> Regression and Matrix Notation</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="5.6-regression-and-matrix-notation.html"><a href="5.6-regression-and-matrix-notation.html#an-intercept-only-model"><i class="fa fa-check"></i><b>5.6.1</b> An Intercept-Only Model</a></li>
<li class="chapter" data-level="5.6.2" data-path="5.6-regression-and-matrix-notation.html"><a href="5.6-regression-and-matrix-notation.html#intercept-only-model-in-matrix-form"><i class="fa fa-check"></i><b>5.6.2</b> Intercept-Only Model in Matrix Form</a></li>
<li class="chapter" data-level="5.6.3" data-path="5.6-regression-and-matrix-notation.html"><a href="5.6-regression-and-matrix-notation.html#simple-regression-in-matrix-form"><i class="fa fa-check"></i><b>5.6.3</b> Simple Regression in Matrix Form</a></li>
<li class="chapter" data-level="5.6.4" data-path="5.6-regression-and-matrix-notation.html"><a href="5.6-regression-and-matrix-notation.html#multiple-regression-in-matrix-form"><i class="fa fa-check"></i><b>5.6.4</b> Multiple Regression in Matrix Form</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="5.7-solving-the-regression-equation.html"><a href="5.7-solving-the-regression-equation.html"><i class="fa fa-check"></i><b>5.7</b> Solving the Regression Equation</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="5.7-solving-the-regression-equation.html"><a href="5.7-solving-the-regression-equation.html#matrix-multiplication-and-transpose"><i class="fa fa-check"></i><b>5.7.1</b> Matrix Multiplication and Transpose</a></li>
<li class="chapter" data-level="5.7.2" data-path="5.7-solving-the-regression-equation.html"><a href="5.7-solving-the-regression-equation.html#matrix-inverse"><i class="fa fa-check"></i><b>5.7.2</b> Matrix Inverse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-chapter-6.html"><a href="6-chapter-6.html"><i class="fa fa-check"></i><b>6</b> Linear Regression in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="6.1-example-data-2.html"><a href="6.1-example-data-2.html"><i class="fa fa-check"></i><b>6.1</b> Example Data</a></li>
<li class="chapter" data-level="6.2" data-path="6.2-intercept-only-model.html"><a href="6.2-intercept-only-model.html"><i class="fa fa-check"></i><b>6.2</b> Intercept-Only Model</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="6.2-intercept-only-model.html"><a href="6.2-intercept-only-model.html#intercept-only-equation"><i class="fa fa-check"></i><b>6.2.1</b> Intercept-Only Equation</a></li>
<li class="chapter" data-level="6.2.2" data-path="6.2-intercept-only-model.html"><a href="6.2-intercept-only-model.html#intercept-only-model-in-r"><i class="fa fa-check"></i><b>6.2.2</b> Intercept-Only Model in R</a></li>
<li class="chapter" data-level="6.2.3" data-path="6.2-intercept-only-model.html"><a href="6.2-intercept-only-model.html#intercept-as-mean-of-outcome"><i class="fa fa-check"></i><b>6.2.3</b> Intercept as Mean of Outcome</a></li>
<li class="chapter" data-level="6.2.4" data-path="6.2-intercept-only-model.html"><a href="6.2-intercept-only-model.html#intercept-only-model-r2"><i class="fa fa-check"></i><b>6.2.4</b> Intercept-Only Model <span class="math inline">\(R^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6.3-simple-linear-regression.html"><a href="6.3-simple-linear-regression.html"><i class="fa fa-check"></i><b>6.3</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="6.3-simple-linear-regression.html"><a href="6.3-simple-linear-regression.html#regression-equation-and-model-fitting"><i class="fa fa-check"></i><b>6.3.1</b> Regression Equation and Model Fitting</a></li>
<li class="chapter" data-level="6.3.2" data-path="6.3-simple-linear-regression.html"><a href="6.3-simple-linear-regression.html#interpreting-model-parameters"><i class="fa fa-check"></i><b>6.3.2</b> Interpreting Model Parameters</a></li>
<li class="chapter" data-level="6.3.3" data-path="6.3-simple-linear-regression.html"><a href="6.3-simple-linear-regression.html#plotting-regression-line"><i class="fa fa-check"></i><b>6.3.3</b> Plotting Regression Line</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6.4-mean-centering-predictors.html"><a href="6.4-mean-centering-predictors.html"><i class="fa fa-check"></i><b>6.4</b> Mean Centering Predictors</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="6.4-mean-centering-predictors.html"><a href="6.4-mean-centering-predictors.html#interpreting-model-parameters-1"><i class="fa fa-check"></i><b>6.4.1</b> Interpreting Model Parameters</a></li>
<li class="chapter" data-level="6.4.2" data-path="6.4-mean-centering-predictors.html"><a href="6.4-mean-centering-predictors.html#plotting-regression-line-1"><i class="fa fa-check"></i><b>6.4.2</b> Plotting Regression Line</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="6.5-multiple-linear-regression.html"><a href="6.5-multiple-linear-regression.html"><i class="fa fa-check"></i><b>6.5</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="6.5-multiple-linear-regression.html"><a href="6.5-multiple-linear-regression.html#regression-equation"><i class="fa fa-check"></i><b>6.5.1</b> Regression Equation</a></li>
<li class="chapter" data-level="6.5.2" data-path="6.5-multiple-linear-regression.html"><a href="6.5-multiple-linear-regression.html#fit-model-in-r"><i class="fa fa-check"></i><b>6.5.2</b> Fit Model in R</a></li>
<li class="chapter" data-level="6.5.3" data-path="6.5-multiple-linear-regression.html"><a href="6.5-multiple-linear-regression.html#plotting-regression-surface"><i class="fa fa-check"></i><b>6.5.3</b> Plotting Regression Surface</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="6.6-categorical-variable-interaction.html"><a href="6.6-categorical-variable-interaction.html"><i class="fa fa-check"></i><b>6.6</b> Categorical Variable Interaction</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="6.6-categorical-variable-interaction.html"><a href="6.6-categorical-variable-interaction.html#interaction-as-moderation"><i class="fa fa-check"></i><b>6.6.1</b> Interaction as Moderation</a></li>
<li class="chapter" data-level="6.6.2" data-path="6.6-categorical-variable-interaction.html"><a href="6.6-categorical-variable-interaction.html#moderation-by-categorical-variable"><i class="fa fa-check"></i><b>6.6.2</b> Moderation by Categorical Variable</a></li>
<li class="chapter" data-level="6.6.3" data-path="6.6-categorical-variable-interaction.html"><a href="6.6-categorical-variable-interaction.html#interpretation"><i class="fa fa-check"></i><b>6.6.3</b> Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="6.7-fit-regression-model-in-r.html"><a href="6.7-fit-regression-model-in-r.html"><i class="fa fa-check"></i><b>6.7</b> Fit Regression Model in R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-chapter-7.html"><a href="7-chapter-7.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Model in R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="7.1-example-data-3.html"><a href="7.1-example-data-3.html"><i class="fa fa-check"></i><b>7.1</b> Example Data</a></li>
<li class="chapter" data-level="7.2" data-path="7.2-the-linear-probability-model.html"><a href="7.2-the-linear-probability-model.html"><i class="fa fa-check"></i><b>7.2</b> The Linear Probability Model</a></li>
<li class="chapter" data-level="7.3" data-path="7.3-link-functions-and-families.html"><a href="7.3-link-functions-and-families.html"><i class="fa fa-check"></i><b>7.3</b> Link Functions and Families</a></li>
<li class="chapter" data-level="7.4" data-path="7.4-binary-outcomes.html"><a href="7.4-binary-outcomes.html"><i class="fa fa-check"></i><b>7.4</b> Binary Outcomes</a></li>
<li class="chapter" data-level="7.5" data-path="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html"><i class="fa fa-check"></i><b>7.5</b> <strong>Logistic Regression</strong>: Empirical example with a Binomial (Bernoulli, binary) distributed outcome variable</a></li>
<li class="chapter" data-level="7.6" data-path="7.6-count-outcomes.html"><a href="7.6-count-outcomes.html"><i class="fa fa-check"></i><b>7.6</b> Count Outcomes</a></li>
<li class="chapter" data-level="7.7" data-path="7.7-poisson-regression-empirical-example-with-counts-as-outcome-variable.html"><a href="7.7-poisson-regression-empirical-example-with-counts-as-outcome-variable.html"><i class="fa fa-check"></i><b>7.7</b> <strong>Poisson Regression</strong>: Empirical example with counts as outcome variable</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-some-take-home-points.html"><a href="8-some-take-home-points.html"><i class="fa fa-check"></i><b>8</b> Some Take-home Points</a></li>
<li class="divider"></li>
<li><a href="https://github.com/zackfisher/HDFS523" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">HDFS 523: Strategies for Data Analysis in Developmental Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> <strong>Logistic Regression</strong>: Empirical example with a Binomial (Bernoulli, binary) distributed outcome variable</h2>
<p>In logistic regression, we are interested in how various predictors are related to the probability of a specific outcome <span class="math inline">\(Pr(Y_i = 1) = \pi_i\)</span>. Making use of the logit link function, the general equation for logistic regression is<br />
<span class="math display">\[logit(\pi_i) = \beta_{0} + \beta_{1}x_1 + ... + \beta_{q}x_q\]</span></p>
<p>Which after back transformation gives us …
<span class="math display">\[ Pr(Y_i = 1) = \pi_i = \frac{e^{\beta_{0} + \beta_{1}x_1 + ... + \beta_{q}x_q}}{1+e^{\beta_{0} + \beta_{1}x_1 + ... + \beta_{q}x_q}} \]</span></p>
<p>For the logistic regression example, let’s shift our focus on the outcome variable <span class="math inline">\(grad_i\)</span>, which indicates whether the mother graduated from high school. The variable ‘grad’ in dataframe ‘wiscsub’ equals 0 if the mother did not graduate high school, and 1 if the mother did graduate high school. Let’s start with the simplest model for predicting ‘grad,’ the intercept-only model. More specifically, we have</p>
<p><span class="math display">\[ logit(\pi_i) = b_0(1_i)\]</span>
where <span class="math inline">\(\pi_i = Pr(grad_i = 1)\)</span>.</p>
<p>We can use the glm() function to fit the model to the data</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb88-1" aria-hidden="true" tabindex="-1"></a>model9 <span class="ot">&lt;-</span> <span class="fu">glm</span>(grad <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb88-2"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb88-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb88-3"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb88-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> wiscsub, </span>
<span id="cb88-4"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb88-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">na.action =</span> na.exclude)</span>
<span id="cb88-5"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model9)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = grad ~ 1, family = &quot;binomial&quot;, data = wiscsub, 
##     na.action = na.exclude)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.7149  -0.7149  -0.7149  -0.7149   1.7260  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.2340     0.1675  -7.365 1.77e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 217.78  on 203  degrees of freedom
## Residual deviance: 217.78  on 203  degrees of freedom
## AIC: 219.78
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The intercept, <span class="math inline">\(b_0\)</span>, reflects the expected log-odds of the outcome variable (log of the ratio of proportions for graduate vs. did not graduate).
<!--Note that odds is a ratio of frequencies while probability is a ratio of one selected outcome, like graduate, to all possible outcomes  --></p>
<p>Sometimes it is easier to communicate results in terms of probabilities, instead of odd. So we can use the inverse link function to get that:
<span class="math display">\[ Pr(grad_i = 1) = \pi_i = \frac{e^{b_0}}{1+e^{b_0}} \]</span></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.2340</span>)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.2340</span>))</span></code></pre></div>
<pre><code>## [1] 0.2254821</code></pre>
<p>The expected probability of the mother graduating is 0.2254821. Let’s confirm that the backward transformed parameter from this intercept-only logistic regression matches the expectation we get from the descriptives of the raw data.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(wiscsub<span class="sc">$</span>grad)</span></code></pre></div>
<pre><code>## [1] 0.2254902</code></pre>
<p>The answers match, both indicate that the expected probability of mother having graduated from high school in this sample is about .225.</p>
<p>Ok, let’s include a predictor. Let’s include <span class="math inline">\(verb^{*}_{1i}\)</span> such that</p>
<p><span class="math display">\[ logit(\pi_i) = b_0(1_i) + b_1(verb^{*}_{1i}) + \epsilon_i \]</span>
where <span class="math inline">\(\pi_i = Pr(grad_i = 1)\)</span>.</p>
<p>And now let’s fit the model</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb94-1" aria-hidden="true" tabindex="-1"></a>model10 <span class="ot">&lt;-</span> <span class="fu">glm</span>(grad <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> verb1_star, </span>
<span id="cb94-2"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb94-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb94-3"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb94-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> wiscsub, </span>
<span id="cb94-4"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb94-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">na.action =</span> na.exclude)</span>
<span id="cb94-5"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model10)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = grad ~ 1 + verb1_star, family = &quot;binomial&quot;, data = wiscsub, 
##     na.action = na.exclude)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5030  -0.6956  -0.5529  -0.3288   2.2344  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.39038    0.18954  -7.336  2.2e-13 ***
## verb1_star   0.13681    0.03278   4.174  3.0e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 217.78  on 203  degrees of freedom
## Residual deviance: 197.87  on 202  degrees of freedom
## AIC: 201.87
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The parameter estimate <span class="math inline">\(b_0\)</span> reflects the expected log-odds of a mother graduating for a child with an average Grade 1 verbal score. Using the inverse link function …</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.39038</span> )<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.39038</span>))</span></code></pre></div>
<pre><code>## [1] 0.1993471</code></pre>
<p>We note that, for the average Grade 1 child (in this sample), there is a .2 probability of having a mother that graduated from high school.</p>
<p>Going back to the model parameters, the estimate for <span class="math inline">\(b_1\)</span> indicates the expected difference of the log-odds of a mother graduating for a 1-point difference in their child’s Grade 1 verbal score. Therefore, we expect a 0.13681 difference in the log-odds of mothers graduating for a 1 point difference in children’s 1st grade verbal score.</p>
<p>Parameter estimates from a logistic regression are often reported in terms of ‘odds’ rather than ‘log-odds.’ To obtain parameters in odds units, we simply exponentiate the coefficients. Note that this is just one of the steps of the inverse link function (which would take us all the way to probability units). Therefore, we have</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model10))</span></code></pre></div>
<pre><code>## (Intercept)  verb1_star 
##   0.2489803   1.1466101</code></pre>
<p>And to obtain 95% confidence intervals for these coefficients, we use</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(model10), <span class="fu">confint</span>(model10)))</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    OR     2.5 %    97.5 %
## (Intercept) 0.2489803 0.1685443 0.3554798
## verb1_star  1.1466101 1.0776626 1.2262119</code></pre>
<p>Using these parameter estimates, we can say that the odds of a mother graduating is 0.2489 if her child had an average first grade verbal score. Also, for each 1-point difference in the child’s 1st grade verbal score we expect a 1.146 difference in the odds of the child’s mother graduating high school.
Communicating results from logistic regression is always difficult, but translation to odds or probabilities can help tremendously. Do what you can to make it easy for your readers.</p>
<p>Here is our model for predicting the probability that the mother graduated:</p>
<p><span class="math display">\[ Pr(grad_i=1) = \pi_i = \frac{e^{-1.39038+0.13681(verb^{*}_{1i})}}{1+e^{-1.39038+0.13681(verb^{*}_{1i})}}\]</span></p>
<p>We can visualize the relation between 1st grade verbal scores and probability of mothers’ graduation in the original 0 to 1 scale.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub,</span>
<span id="cb103-2"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>verb1_star,<span class="at">y=</span>grad)) <span class="sc">+</span></span>
<span id="cb103-3"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">08</span>, <span class="at">size =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb103-4"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="st">&quot;1st Grade Verbal Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb103-5"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="st">&quot;Mothers&#39; Graduation&quot;</span>) <span class="sc">+</span></span>
<span id="cb103-6"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb103-7"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb103-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;glm&#39;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">se =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>We can see that with higher 1st grade verbal scores, the probability of mothers having graduated is higher.</p>
<p>Notice how the density of the observations is visualized by manipulating the transparency (alpha) level of the data points. The predicted curve based on our model has of course a non-linear shape (however, if we were to plot the relationship between the variables with using the logit link, it would be a straight line).</p>
<p>Ok, let’s include another predictor. Let’s look at verbal score and gender.</p>
<p><span class="math display">\[ logit(\pi_i) = b_0 + b_1(verb^{*}_{1i}) + b_2(female_i) + b_3(verb^{*}_{1i})(female_i) \]</span>
where <span class="math inline">\(\pi_i = Pr(grad_i = 1)\)</span>.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb105-1" aria-hidden="true" tabindex="-1"></a>model11 <span class="ot">&lt;-</span> <span class="fu">glm</span>(grad <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> female <span class="sc">+</span> verb1_star <span class="sc">+</span> <span class="fu">I</span>(verb1_star<span class="sc">*</span>female) , </span>
<span id="cb105-2"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb105-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb105-3"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb105-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> wiscsub, </span>
<span id="cb105-4"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb105-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">na.action =</span> na.exclude)</span>
<span id="cb105-5"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model11)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = grad ~ 1 + female + verb1_star + I(verb1_star * 
##     female), family = &quot;binomial&quot;, data = wiscsub, na.action = na.exclude)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4224  -0.6894  -0.5705  -0.2692   2.4419  
## 
## Coefficients:
##                        Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)            -1.38195    0.25825  -5.351 8.73e-08 ***
## female                 -0.07282    0.38885  -0.187   0.8514    
## verb1_star              0.09119    0.04146   2.200   0.0278 *  
## I(verb1_star * female)  0.11490    0.06987   1.644   0.1001    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 217.78  on 203  degrees of freedom
## Residual deviance: 194.79  on 200  degrees of freedom
## AIC: 202.79
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Parameters <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> describe the relation between <span class="math inline">\(verb^{*}_{1i}\)</span> and <span class="math inline">\(grad_i\)</span> for males, and <span class="math inline">\(b_0 + b_2\)</span> and <span class="math inline">\(b_1 + b_3\)</span> describe the relation for females. Note that neither <span class="math inline">\(b_2\)</span> nor <span class="math inline">\(b_3\)</span> are significantly different from zero, so boys and girls have about the same relation between 1st grade verbal scores and the number of years of mothers’ education.</p>
<p>We can see this first on the log-odds scale as</p>
<p><span class="math display">\[ logit(\pi_i) = -1.38195  + 0.09119(verb^{*}_{1i}) -0.07282(female_i)+  0.11490 (verb^{*}_{1i})(female_i) \]</span>
where <span class="math inline">\(\pi_i = Pr(grad_i = 1)\)</span>.</p>
<p>Transformed to the probability (0 to 1) scale, this is</p>
<p><span class="math display">\[ grad_i = \frac{e^{-1.38195  + 0.09119(verb^{*}_{1i})+ 0.0162466(female_i)+  0.11490 (verb^{*}_{1i})(female_i)}}{1+e^{-1.38195  + 0.09119(verb^{*}_{1i})+ 0.0162466(female_i)+  0.11490 (verb^{*}_{1i})(female_i)}} \]</span></p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>wiscsub,</span>
<span id="cb107-2"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">aes</span>(<span class="at">x=</span>verb1_star,<span class="at">y=</span>grad, <span class="at">color =</span> <span class="fu">factor</span>(female))) <span class="sc">+</span></span>
<span id="cb107-3"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">08</span>, <span class="at">size =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb107-4"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="st">&quot;1st Grade Verbal Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-5"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="st">&quot;Mothers&#39; Graduation&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-6"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">guides</span>(<span class="at">color=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="st">&quot;Female&quot;</span>)) <span class="sc">+</span>  </span>
<span id="cb107-7"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb107-8"><a href="7.5-logistic-regression-empirical-example-with-a-binomial-bernoulli-binary-distributed-outcome-variable.html#cb107-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;glm&#39;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p>So, in summary, fitting linear models to binary outcomes is very similar to fitting models to Gaussian outcomes. We use the logit link function to normalize the outcome variable, and then all of the parameter estimates are in terms of log-odds. Transformation back into the probability space may provide for easier interpretation.</p>
<p>What the equivalent of an R-square is, is not clear …
Relevant info and discussion can be found in the following places -</p>
<p><a href="http://statisticalhorizons.com/r2logistic" class="uri">http://statisticalhorizons.com/r2logistic</a></p>
<p><a href="http://stats.stackexchange.com/questions/3559/which-pseudo-r2-measure-is-the-one-to-report-for-logistic-regression-cox-s?rq=1" class="uri">http://stats.stackexchange.com/questions/3559/which-pseudo-r2-measure-is-the-one-to-report-for-logistic-regression-cox-s?rq=1</a></p>
<p>with general info on pseudo R-sq here
<a href="http://statistics.ats.ucla.edu/stat/mult_pkg/faq/general/Psuedo_RSquareds.htm" class="uri">http://statistics.ats.ucla.edu/stat/mult_pkg/faq/general/Psuedo_RSquareds.htm</a></p>
<p>and it looks like R-specifc implementation can be done with …
Harrell’s rms package gives Nagalkerke’s R2
<a href="http://stats.stackexchange.com/questions/8511/how-to-calculate-pseudo-r2-from-rs-logistic-regression" class="uri">http://stats.stackexchange.com/questions/8511/how-to-calculate-pseudo-r2-from-rs-logistic-regression</a>
or for McFadden’s R2 the pR2() function in the pscl library (as noted in the second answer)</p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="7.4-binary-outcomes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="7.6-count-outcomes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/zackfisher/HDFS523/edit/master/07_glm_in_r.Rmd",
"text": "Suggest an edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
